Repository projectcalico/kube-controllers, pull requests merged in 2019-11, with the labels that each got.

#426 [release-v3.10] Automatic patch of libcalico-go to 8f81e1e344ce1dc436b066ea242e4da5df765a97
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#427 [release-v3.9] Automatic patch of libcalico-go to 1891db7ae73bcafe01c90943f5eaac25ec53c96d
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#428 Tidy go.sum
  go.sum
Labels: docs-pr-required, release-note-required

#429 Move "Extra Args" Up in the world
  Makefile
Labels: docs-pr-required, release-note-required

#430 Fix packagename plumbing for -w option
  Makefile
Labels: docs-pr-required, release-note-required

#431 Update amd64 images to meet certification requirements
  Dockerfile.amd64
  Makefile
  docker-images/flannel-migration/Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#432 Fix nil map for flannel migration.
  pkg/controllers/flannelmigration/k8s_resources.go
Labels: docs-not-required, release-note-required

#433 Fix "clean" functionality in kube-controllers.
  Makefile
Labels: docs-not-required, release-note-not-required

#434 Move common Makefile targets to Makefile.common
  Makefile
  cmd/kube-controllers/main.go
  go.mod
  go.sum
  tests/fv/kdd_node_ipam_test.go
  tests/testutils/utils.go
Labels: docs-not-required, release-note-not-required

#436 Switch Makefile.common from wget to curl, remove wget dependency
  Makefile
Labels: docs-not-required, release-note-not-required

#437 client-go v12.0.0 -> client-go v0.0.0-20191008115822-1210218b4a26 (hi…
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#438 Fix nil map for flannel migration.
  pkg/controllers/flannelmigration/k8s_resources.go
Labels: docs-pr-required, release-note-required

#440 Move image build/push targets back to local Makefile
  Makefile
Labels: docs-not-required, release-note-not-required
