Repository projectcalico/kube-controllers, pull requests merged in 2019-10, with the labels that each got.

#413 need to harden go mod downloads against network errors
  Makefile
Labels: docs-not-required, release-note-not-required

#417 Update pins correctly
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#416 [release-v3.10] Automatic update of libcalico-go to 399044ecb65942961586f38c38415d95b9122dcc
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#419 Token projection support
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#418 Token projection support
  cmd/kube-controllers/main.go
  glide.lock
  glide.yaml
  pkg/controllers/namespace/namespace_controller.go
  pkg/controllers/pod/pod_controller.go
  pkg/controllers/serviceaccount/serviceaaccount_controller.go
Labels: docs-not-required, release-note-not-required

#422 Don't klog to disk
  cmd/kube-controllers/main.go
Labels: docs-not-required, release-note-required

#423 Remove 'undo' behavior from local_build
  Makefile
Labels: docs-not-required, release-note-not-required

#425 fix some typo
  pkg/converter/converter.go
  pkg/converter/namespace_converter.go
  pkg/converter/networkpolicy_converter.go
  pkg/converter/serviceaccount_converter.go
Labels: docs-not-required, release-note-not-required
