Repository projectcalico/kube-controllers, pull requests merged in 2020-04, with the labels that each got.

#466 Fix watch race in test_config
  pkg/config/config_test.go
Labels: docs-pr-required, release-note-not-required

#467 Handle mismatched nodenames in etcd mode IPAM cleanup
  go.mod
  go.sum
  pkg/controllers/node/ipam.go
  pkg/controllers/node/node_syncer.go
  tests/fv/etcd_node_ipam_test.go
  tests/fv/kdd_node_ipam_test.go
  tests/fv/node_auto_hep_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#468 [v3.13 cherry pick] Handle mismatched nodenames in etcd mode IPAM cleanup (#467)
  go.mod
  go.sum
  pkg/controllers/flannelmigration/ipam_migrator.go
  pkg/controllers/node/ipam.go
  pkg/controllers/node/node_controller.go
  pkg/controllers/node/node_syncer.go
  tests/fv/etcd_node_ipam_test.go
  tests/fv/flannel_migration_test.go
  tests/fv/kdd_node_ipam_test.go
  tests/testutils/utils.go
Labels: docs-not-required, release-note-required

#463 Update go-build to v0.37
  Makefile
Labels: docs-not-required, release-note-not-required

#469 Update libcalico pin, handle conversion from pod to multiple WEPs
  go.mod
  go.sum
  pkg/controllers/pod/pod_controller.go
  pkg/converter/namespace_converter.go
  pkg/converter/networkpolicy_converter.go
  pkg/converter/pod_converter.go
  pkg/converter/pod_converter_test.go
  pkg/converter/serviceaccount_converter.go
Labels: docs-not-required, release-note-not-required

#470 auto host endpoints have a default allow profile
  Makefile
  go.mod
  go.sum
  pkg/controllers/node/hostendpoints.go
  tests/fv/node_auto_hep_test.go
  tests/testutils/node_controller_utils.go
Labels: docs-pr-required, release-note-required

#471 Update of libcalico-go pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#474 Commit to try to fix dirty build
  go.sum
Labels: docs-not-required, release-note-not-required

#472 Don't skip processing auto heps if node label syncing is skipped
  cmd/kube-controllers/main.go
  pkg/controllers/node/node_syncer.go
  tests/fv/node_auto_hep_test.go
  tests/testutils/node_controller_utils.go
Labels: docs-not-required, release-note-not-required

#475 Update of libcalico pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#476 Fix watch on kubecontrollersconfigurations
  Makefile
  pkg/config/config_test.go
  pkg/config/runconfig.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required
