Repository projectcalico/kube-controllers, pull requests merged in 2020-08, with the labels that each got.

#494 Remove vendor dir if it exists on clean
  Makefile
Labels: docs-not-required, release-note-required

#497 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#498 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#501 Update pins
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required
