Repository projectcalico/kube-controllers, pull requests merged in 2020-12, with the labels that each got.

#566 Automated cherry pick of #565: Run kube-controllers as non-root by default
  Dockerfile.amd64
  Makefile
  docker-images/flannel-migration/Dockerfile.amd64
  pkg/status/status.go
  tests/fv/config_test.go
  tests/fv/etcd_node_ipam_test.go
  tests/fv/flannel_migration_test.go
  tests/fv/fv_resiliency_test.go
  tests/fv/fv_test.go
  tests/fv/kdd_node_ipam_test.go
  tests/fv/node_auto_hep_test.go
  tests/fv/node_label_test.go
  tests/testutils/policy_controller_utils.go
Labels: docs-pr-required, release-note-required

#572 Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-pr-required, release-note-required

#573 Automated cherry pick of #572: Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-not-required, release-note-not-required

#574 Automated cherry pick of #572: Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-pr-required, release-note-required

#577 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#580 Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-not-required, release-note-not-required

#581 Automated cherry pick of #580: Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-pr-required, release-note-required
