Repository projectcalico/kube-controllers, pull requests merged in 2020-10, with the labels that each got.

#525 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#527 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#529 Update go-build version to v0.48 (go 1.15.2)
  Makefile
Labels: docs-not-required, release-note-not-required

#530 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#531 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#533 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#535 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#536 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#537 Watch termination
  pkg/config/config_test.go
  pkg/config/runconfig.go
Labels: docs-not-required, release-note-not-required

#539 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#538 ErrorWatchTerminated error is no longer used
  pkg/config/config_test.go
  pkg/config/runconfig.go
Labels: docs-pr-required, release-note-required
