Repository projectcalico/kube-controllers, pull requests merged in 2020-09, with the labels that each got.

#496 Handle multi-master flannel migration
  pkg/controllers/flannelmigration/migration_controller.go
Labels: docs-not-required, release-note-required

#502 Fix `kubectl exec` format for migration controller
  pkg/controllers/flannelmigration/k8s_resources.go
Labels: docs-pr-required, release-note-required

#503 Automated cherry pick of #496: Handle multi-master flannel migration
  pkg/controllers/flannelmigration/migration_controller.go
Labels: docs-not-required, release-note-required

#504 Automated cherry pick of #502: Fix `kubectl exec` format for migration controller
  pkg/controllers/flannelmigration/k8s_resources.go
Labels: docs-not-required, release-note-required

#505 Update flannel migration controller for Rancher
  pkg/controllers/flannelmigration/k8s_resources.go
  pkg/controllers/flannelmigration/migration_controller.go
Labels: docs-not-required, release-note-required

#506 Automated cherry pick of #505: Update migration controller for rancher
  pkg/controllers/flannelmigration/k8s_resources.go
  pkg/controllers/flannelmigration/migration_controller.go
Labels: docs-not-required, release-note-required

#508 [release-v3.16] Update pins
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#509 [release-v3.15] Update pins
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#510 Update migration controller comments
  pkg/controllers/flannelmigration/migration_controller.go
Labels: docs-pr-required, release-note-required

#512 Fix cleanup of wireguard IP addresses for deleted nodes
  pkg/controllers/node/ipam.go
  tests/fv/kdd_node_ipam_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#516 Semaphore v2 migration / add pin update pipeline
  .semaphore/clear_cache.yml
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
  Makefile
  tests/fv/kdd_node_ipam_test.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#519 Allow semaphore-run-auto-pin-update-workflows to set the SEMAPHORE_PROJECT_ID (only default it if it's not set)
  Makefile
Labels: docs-not-required, release-note-not-required
