Repository projectcalico/kube-controllers, pull requests merged in 2020-11, with the labels that each got.

#540 [master] Automatic update of sempahore YAMLs.
  .semaphore/clear_cache.yml
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-pr-required, release-note-required

#541 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#543 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#542 Fix release branch pin update regex (add ^ to start)
  .semaphore/semaphore.yml
  Makefile
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#544 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#545 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#547 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#549 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#550 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#554 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#553 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#555 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#548 Add a command line flag to set status file path
  cmd/kube-controllers/main.go
Labels: docs-pr-required, release-note-required

#556 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#558 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#557 Add a test to verify improperly formatted handles
  Makefile
  tests/fv/kdd_node_ipam_test.go
Labels: docs-not-required, release-note-not-required

#560 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#562 update pins
  cmd/kube-controllers/main.go
  go.mod
  go.sum
  pkg/controllers/flannelmigration/k8s_resources.go
  pkg/controllers/node/etcd.go
  pkg/controllers/node/ipam.go
  tests/fv/config_test.go
  tests/fv/etcd_node_ipam_test.go
  tests/fv/flannel_migration_test.go
  tests/fv/fv_resiliency_test.go
  tests/fv/fv_test.go
  tests/fv/kdd_node_ipam_test.go
  tests/fv/node_auto_hep_test.go
  tests/fv/node_label_test.go
  tests/testutils/flannel_migration_utils.go
Labels: docs-not-required, release-note-not-required

#563 [master] Semaphore Auto Pin Update
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
