Repository projectcalico/kube-controllers, pull requests merged in 2020-01, with the labels that each got.

#445 release-v3.10 - Update libcalico-go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#444 release-v3.8 - Update libcalico-go so we use go-yaml v2.25
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#446 release-v3.9 - Update libcalico-go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#449 release-v3.8 - Update felix
  glide.lock
Labels: docs-not-required, release-note-required

#450 release-v3.9 - Update felix
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#451 release-v3.10 - Update felix
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#452 Add in missing dependency to go.mod
  go.mod
Labels: docs-not-required, release-note-not-required

#442 Remove IgnoreLooseRPF
  tests/fv/fv_test.go
Labels: docs-not-required, release-note-not-required

#453 Fix flannel-migration tagging
  Makefile
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#454 Fix flannel-migration tagging (pick #453)
  Makefile
Labels: docs-not-required, release-note-not-required

#456 Fix test to account for new labels
  go.mod
  go.sum
  pkg/converter/namespace_converter_test.go
  pkg/converter/serviceaccount_converter_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#457 Pick #456 to release-v3.12
  go.mod
  go.sum
  pkg/converter/namespace_converter_test.go
  pkg/converter/serviceaccount_converter_test.go
Labels: docs-not-required, release-note-not-required
