Repository projectcalico/kube-controllers, pull requests merged in 2021-03, with the labels that each got.

#636 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#635 Increase semaphore job timeout
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#638 Automated cherry pick of #635: Increase semaphore job timeout
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#639 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#641 Call handleErr unconditionally
  pkg/controllers/namespace/namespace_controller.go
  pkg/controllers/pod/pod_controller.go
  pkg/controllers/serviceaccount/serviceaaccount_controller.go
Labels: docs-not-required, release-note-required

#642 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#643 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#644 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#645 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#647 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#646 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#648 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#649 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#650 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#652 Update pins
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#653 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#654 Update pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#656 [release-v3.18] Semaphore Auto Pin Update
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#659 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#660 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#661 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#662 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#663 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#664 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#665 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#666 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#668 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
