Repository projectcalico/kube-controllers, pull requests merged in 2021-11, with the labels that each got.

#895 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#896 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#897 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#899 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#900 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#902 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#901 IPAM GC now spots when two IPs have the same handle
  pkg/controllers/node/ipam.go
  pkg/controllers/node/ipam_allocation.go
  pkg/controllers/node/ipam_test.go
Labels: release-note-required, cherry-pick-candidate, docs-not-required

#903 Automated cherry pick of #901: Don't release IPs if another IP with the same handle is
  pkg/controllers/node/ipam.go
  pkg/controllers/node/ipam_allocation.go
  pkg/controllers/node/ipam_test.go
Labels: release-note-required, docs-not-required

#904 Automated cherry pick of #901: Don't release IPs if another IP with the same handle is
  pkg/controllers/node/ipam.go
  pkg/controllers/node/ipam_allocation.go
  pkg/controllers/node/ipam_test.go
Labels: release-note-required, docs-not-required

#905 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#906 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#907 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#908 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#909 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#910 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#911 Fix case where we weren't deleting block from blocksByNode
  pkg/controllers/node/ipam.go
  pkg/controllers/node/ipam_test.go
Labels: release-note-required, docs-not-required

#912 Automated cherry pick of #911: Fix case where we weren't deleting block from
  pkg/controllers/node/ipam.go
  pkg/controllers/node/ipam_test.go
Labels: release-note-required, docs-not-required

#913 Automated cherry pick of #911: Fix case where we weren't deleting block from
  pkg/controllers/node/ipam.go
  pkg/controllers/node/ipam_test.go
Labels: release-note-required, docs-not-required

#914 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#915 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#916 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#917 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#918 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#919 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
