Repository projectcalico/kube-controllers, pull requests merged in 2021-06, with the labels that each got.

#742 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#640 Add armv7 build
  Dockerfile.armv7
  Makefile
  docker-images/flannel-migration/Dockerfile.armv7
Labels: docs-not-required, merge-when-ready, release-note-not-required

#743 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#745 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#746 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#747 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#748 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#749 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-pr-required, release-note-required

#750 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#744 IP address garbage collection
  .gitignore
  cmd/kube-controllers/main.go
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/runconfig.go
  pkg/controllers/node/controller.go
  pkg/controllers/node/errors.go
  pkg/controllers/node/etcd.go
  pkg/controllers/node/fake_client.go
  pkg/controllers/node/hostendpoints.go
  pkg/controllers/node/ipam.go
  pkg/controllers/node/ipam_allocation.go
  pkg/controllers/node/ipam_test.go
  pkg/controllers/node/labels.go
  pkg/controllers/node/node_controller.go
  pkg/controllers/node/node_deleter.go
  pkg/controllers/node/node_suite_test.go
  pkg/controllers/node/node_syncer.go
  pkg/controllers/node/syncer.go
  pkg/controllers/pod/pod_controller.go
  tests/fv/config_test.go
  tests/fv/fv_test.go
  tests/fv/kdd_ipam_gc_test.go
  tests/fv/kdd_node_ipam_test.go
Labels: docs-completed, release-note-required

#753 Replace lib/v3 package with projectcalico/api
  go.mod
  go.sum
  pkg/config/config_test.go
  pkg/config/runconfig.go
  pkg/controllers/flannelmigration/ipam_migrator.go
  pkg/controllers/namespace/namespace_controller.go
  pkg/controllers/networkpolicy/policy_controller.go
  pkg/controllers/node/hostendpoints.go
  pkg/controllers/node/ipam.go
  pkg/controllers/node/ipam_test.go
  pkg/controllers/pod/pod_controller.go
  pkg/controllers/serviceaccount/serviceaaccount_controller.go
  pkg/converter/namespace_converter.go
  pkg/converter/namespace_converter_test.go
  pkg/converter/networkpolicy_converter.go
  pkg/converter/networkpolicy_converter_test.go
  pkg/converter/serviceaccount_converter.go
  pkg/converter/serviceaccount_converter_test.go
  tests/fv/config_test.go
  tests/fv/etcd_node_ipam_test.go
  tests/fv/flannel_migration_test.go
  tests/fv/fv_resiliency_test.go
  tests/fv/fv_test.go
  tests/fv/kdd_ipam_gc_test.go
  tests/fv/kdd_node_ipam_test.go
  tests/fv/metrics_test.go
  tests/fv/node_auto_hep_test.go
Labels: docs-pr-required, release-note-required

#754 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#755 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#756 Update api pins on pin update
  Makefile
Labels: docs-not-required, release-note-not-required

#757 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#759 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#761 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#762 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#763 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#764 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#765 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
