Repository projectcalico/kube-controllers, pull requests merged in 2021-08, with the labels that each got.

#821 Fix duplicate deletion attempts while GCing old blocks
  pkg/controllers/node/ipam.go
Labels: docs-pr-required, release-note-required

#822 Automated cherry pick of #821: Fix duplicate deletion attempts while GCing old blocks
  pkg/controllers/node/ipam.go
Labels: docs-not-required, release-note-required

#808 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#824 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#825 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#826 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#827 Change release repo to docker.io, add RELEASE and CONFIRM env variabl…
  Makefile
Labels: docs-not-required, release-note-not-required

#830 Automated cherry pick of #827: Change release repo to docker.io, add RELEASE and CONFIRM env
  Makefile
Labels: release-note-required, docs-pr-required

#831 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#832 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#833 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#834 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#835 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#836 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#838 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
  tests/fv/fv_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#839 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#842 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch
