Repository projectcalico/kube-controllers, pull requests merged in 2022-02, with the labels that each got.

#925 Update to UBI 8.5 and go-build v0.54
  Dockerfile.amd64
  Makefile
  docker-images/flannel-migration/Dockerfile.amd64
Labels: release-note-required, docs-pr-required

#927 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#926 Update UBI to 8.5
  Dockerfile.amd64
  docker-images/flannel-migration/Dockerfile.amd64
Labels: release-note-required, docs-not-required
